// Hand-written (no vite-plugin-pwa): the precache manifest is generated by
// scripts/pack-encrypted.mjs AFTER `vite build` runs, since it lists files
// (data/*.bin, img/*.bin) that don't exist until encryption happens post-build.
// Everything cached here is already encrypted — this never touches plaintext.
const CACHE_PREFIX = 'topik4-'

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const res = await fetch('precache-manifest.json', { cache: 'no-store' })
      const { dataVersion, urls } = await res.json()
      const cache = await caches.open(CACHE_PREFIX + dataVersion)
      await cache.addAll(urls)
    })()
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const res = await fetch('precache-manifest.json', { cache: 'no-store' })
      const { dataVersion } = await res.json()
      const currentCache = CACHE_PREFIX + dataVersion
      for (const name of await caches.keys()) {
        if (name.startsWith(CACHE_PREFIX) && name !== currentCache) await caches.delete(name)
      }
      await self.clients.claim()
    })()
  )
})

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return
  event.respondWith(
    (async () => {
      const cached = await caches.match(event.request)
      if (cached) return cached
      try {
        return await fetch(event.request)
      } catch (err) {
        if (cached) return cached
        throw err
      }
    })()
  )
})

self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting()
})
